### ISSUE TITLE
Plan & design Phi Software social media content for September 2022

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#100]
Social Media: Instagram (https://www.instagram.com/phisoft.my/) & Facebook (https://www.facebook.com/phisoft.my)
- [ ] prepare at least 2 post for each week (8 posts)
- [ ] place the content in a zip file

**Comment by rosclaritha** [comment]
[Untitled design(21).zip](https://github.com/phisoft/phisoft-web/files/9503299/Untitled.design.21.zip)

**Comment by lalgal** [comment]
[PhiSoft Introduction - 9 Sept 2022.zip](https://github.com/phisoft/phisoft-web/files/9533648/PhiSoft.Introduction.-.9.Sept.2022.zip)

**Comment by lalgal** [comment]
[What Most People Think Of Developers.zip](https://github.com/phisoft/phisoft-web/files/9533678/What.Most.People.Think.Of.Developers.zip)

**Comment by lalgal** [comment]
[Never lose a document with KertasDMS - 13 Sept 2022.zip](https://github.com/phisoft/phisoft-web/files/9554690/Never.lose.a.document.with.KertasDMS.-.13.Sept.2022.zip)

**Comment by rosclaritha** [comment]
@lalgal change the font color

![Image](https://user-images.githubusercontent.com/30463117/190047659-a32fa020-30e4-4043-8624-a6fe73dc700e.jpg)

**Comment by lalgal** [comment]
![Marketing Content - 3 Sept 2022](https://user-images.githubusercontent.com/112998668/190054496-a31cca5b-6db9-4d66-b37c-caf0b382ec2a.jpg)

**Comment by lalgal** [comment]
[Never lose a document with KertasDMS - 13 Sept 2022.zip](https://github.com/phisoft/phisoft-web/files/9562473/Never.lose.a.document.with.KertasDMS.-.13.Sept.2022.zip)

**Comment by lalgal** [comment]
[Lighten the load - 14 Sept 2022.zip](https://github.com/phisoft/phisoft-web/files/9562589/Lighten.the.load.-.14.Sept.2022.zip)

**Comment by lalgal** [comment]
[Marketing Content - 20 Sept 2022.zip](https://github.com/phisoft/phisoft-web/files/9604413/Marketing.Content.-.20.Sept.2022.zip)
