### ISSUE TITLE
Design TicketBos solution story

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#102]
You can view the sample on @phisoft.my Instgram highlights. 

TicketBos website link: https://www.ticketbos.com/

Sample: 
![Image](https://user-images.githubusercontent.com/30463117/188805613-15a774dd-2e80-41b1-9ee7-e7a8a6b9452a.png)
![Image](https://user-images.githubusercontent.com/30463117/188805644-9d246f6a-ba45-4a19-bcd7-02be90aa306d.png)
![Image](https://user-images.githubusercontent.com/30463117/188805679-0c7b67a0-93b0-4b98-ba63-17c9ffb7545d.png)

To know more about our company products, visit the following link: https://www.phisoft.my/our-solutions.html

**Comment by lalgal** [comment]
[Ticketbos Solution Story.zip](https://github.com/phisoft/phisoft-web/files/9525352/Ticketbos.Solution.Story.zip)

**Comment by rosclaritha** [comment]
@lalgal Make the following modifications:
- [ ] follow the original logo color theme
https://github.com/phisoft/ticketbos-addons
- [ ] try to minimize colors
![Image](https://user-images.githubusercontent.com/30463117/189802784-30d8a158-0fbb-47f1-b023-33028c4f8675.png)
- [ ] simplify the content copywriting

*provide screenshots of the designs rather than zipped file for easy viewing

**Comment by lalgal** [comment]
![Ticketbos Story 1](https://user-images.githubusercontent.com/112998668/189814732-cfec168c-cc0d-4f66-a21f-385010ae2044.jpg)
![Ticketbos Story 2](https://user-images.githubusercontent.com/112998668/189814737-1b6013c8-a2d6-4613-9c1e-cee47b38cedb.jpg)
![Ticketbos Story 3](https://user-images.githubusercontent.com/112998668/189814739-903da619-5c43-4f06-8777-13aa4ef06b90.jpg)
![Ticketbos Story 4](https://user-images.githubusercontent.com/112998668/189814744-837d18ea-8c71-4915-b06e-7918149ffb5f.jpg)
![Ticketbos Story 5](https://user-images.githubusercontent.com/112998668/189814747-9268a028-d3d0-4d3f-93c9-20e0f626f307.jpg)
![Ticketbos Story 6](https://user-images.githubusercontent.com/112998668/189814753-e2361e3f-8aac-4b9c-951c-85b72348c097.jpg)
