### ISSUE TITLE
Design half A4 ads for APPS magazine

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#103]

**Comment by lalgal** [comment]
[Ads for APPS Magazine.zip](https://github.com/phisoft/phisoft-web/files/9545620/Ads.for.APPS.Magazine.zip)

**Comment by lalgal** [comment]
![Image](https://user-images.githubusercontent.com/112998668/190310524-d62fee22-48f6-4c98-950b-8e0158398b07.jpg)

**Comment by lalgal** [comment]
![Image](https://user-images.githubusercontent.com/112998668/190310524-d62fee22-48f6-4c98-950b-8e0158398b07.jpg)

**Comment by lalgal** [comment]
![Image](https://user-images.githubusercontent.com/112998668/190328082-faec3b8a-2bbf-4327-97e8-a37ba3bd455f.jpg)

**Comment by lalgal** [comment]
[Ads for APPS Magazine.zip](https://github.com/phisoft/phisoft-web/files/9572368/Ads.for.APPS.Magazine.zip)
