### ISSUE TITLE
Design half A4 ads for DentalLink - APPS Magazine

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#105]
Website: https://www.dentallinkapp.com/
System access: demo.dentallinkapp.com/
Email / Password: admin / admin

**Comment by lalgal** [comment]
[Dental Link Website Banner.zip](https://github.com/phisoft/phisoft-web/files/9553640/Dental.Link.Website.Banner.zip)

**Comment by lalgal** [comment]
![Image](https://user-images.githubusercontent.com/112998668/190331336-80924c70-2490-4924-b273-a4fe7a12cc48.jpg)

**Comment by lalgal** [comment]
[Dental Link - Apps Mag.zip](https://github.com/phisoft/phisoft-web/files/9572524/Dental.Link.-.Apps.Mag.zip)
