### ISSUE TITLE
Design 10 posters relating to tech knowledge

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#110]

**Comment by rosclaritha** [comment]
![Image](https://user-images.githubusercontent.com/30463117/190045840-9251a431-0a3c-4014-9b30-482f0be79283.png)

![Image](https://user-images.githubusercontent.com/30463117/190047193-3d2f76be-1304-4bcb-8636-458a930de76d.png)

**Comment by lalgal** [comment]
[10 Tech Knowledge.zip](https://github.com/phisoft/phisoft-web/files/9597173/10.Tech.Knowledge.zip)
