### ISSUE TITLE
Redesign facebook header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#111]
![Image](https://user-images.githubusercontent.com/30463117/190055596-8cac3ab3-2b54-4601-877f-35e3d305d082.png)

**Comment by lalgal** [comment]
![FB Banner - Phi Software 1](https://user-images.githubusercontent.com/112998668/190072908-095317bd-4591-4b9c-a642-f2bf556b8dd5.jpg)

**Comment by lalgal** [comment]
[FB Banner - Phi Software 1.zip](https://github.com/phisoft/phisoft-web/files/9563187/FB.Banner.-.Phi.Software.1.zip)

**Comment by rosclaritha** [comment]
Provide a few more designs for the Facebook header @lalgal

**Comment by lalgal** [comment]
![Laptop Mockup Compilation](https://user-images.githubusercontent.com/112998668/193194606-0b877375-6c82-49a3-8089-b5d1d9ce613b.jpg)

**Comment by lalgal** [comment]
![Phone Mockup Compilation](https://user-images.githubusercontent.com/112998668/193194651-1d5ad997-2205-4240-aa79-d1420ed3a54e.jpg)

**Comment by lalgal** [comment]
[FB Banner - Phi Software.zip](https://github.com/phisoft/phisoft-web/files/9680922/FB.Banner.-.Phi.Software.zip)

**Comment by lalgal** [comment]
[FB Banner - Phi Software.zip](https://github.com/phisoft/phisoft-web/files/9681464/FB.Banner.-.Phi.Software.zip)
