### ISSUE TITLE
Design ticket template for ticketbos

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#112]
You can try to find other samples also. 
![Image](https://user-images.githubusercontent.com/30463117/190057906-f64c7a00-e34f-4597-8e2a-7fdfba56b46a.png)

![Image](https://user-images.githubusercontent.com/30463117/190058049-9a030fce-37f9-474b-8da5-c1ad7bc1338a.png)

**Comment by lalgal** [comment]
[Design Ticketbos.zip](https://github.com/phisoft/phisoft-web/files/9563108/Design.Ticketbos.zip)

**Comment by lalgal** [comment]
![Image](https://user-images.githubusercontent.com/112998668/190329205-8058b7a0-ac6d-4865-aac0-4b039b6552eb.jpg)
