### ISSUE TITLE
Update linked main banner

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#128]

**Comment by paragasu** [comment]
![Image](https://user-images.githubusercontent.com/27353/191711631-08540c54-277d-4a45-8c87-31ef9a27c0d9.png)

**Comment by lalgal** [comment]
![Mockup](https://user-images.githubusercontent.com/112998668/192932516-c28ff4f4-b115-4055-bea9-91be6870e014.jpg)

**Comment by lalgal** [comment]
[LinkedIn Banner.zip](https://github.com/phisoft/phisoft-web/files/9670692/LinkedIn.Banner.zip)

**Comment by rosclaritha** [comment]
Provide a few more designs @lalgal
