### ISSUE TITLE
Plan & design Phi Software social media content for October 2022

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#130]
- [ ] quotes
- [ ] tech knowledge
- [ ] q&a
- [ ] promote our services
- [ ] interesting contents
- [ ] deepavali

**Comment by lalgal** [comment]
[Quote by Edsger Wybe Dijkstra.zip](https://github.com/phisoft/phisoft-web/files/9796350/Quote.by.Edsger.Wybe.Dijkstra.zip)

**Comment by lalgal** [comment]
[Deepavali Greeting.zip](https://github.com/phisoft/phisoft-web/files/9796384/Deepavali.Greeting.zip)

**Comment by lalgal** [comment]
[Stopping Burnout - LINK.zip](https://github.com/phisoft/phisoft-web/files/9856663/Stopping.Burnout.-.LINK.zip)
