### ISSUE TITLE
Provide map/ location design for website background

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#133]
On https://www.phisoft.my/contacts.html, need to change the background image of the following to maps or something similar. Provide a few suitable designs.

![Image](https://user-images.githubusercontent.com/30463117/194979565-a720b0b1-d6c0-40c5-9a54-efc27c050fca.png)

**Comment by rosclaritha** [comment]
Provide more design related to maps and location background @lalgal

**Comment by lalgal** [comment]
![Mockup - Phisoftware (Contacts) 2](https://user-images.githubusercontent.com/112998668/195026088-31932751-5308-4ff0-81c3-44669475f8d6.jpg)

**Comment by lalgal** [comment]
[Design PhiSoft (Contacts).zip](https://github.com/phisoft/phisoft-web/files/9752304/Design.PhiSoft.Contacts.zip)

**Comment by lalgal** [comment]
![Design 6 - PhiSoft (Contacts) Mockup](https://user-images.githubusercontent.com/112998668/195531655-5c262246-4e13-473e-b5ae-9827180760f8.jpg)

**Comment by lalgal** [comment]
[Design 6 - PhiSoft (Contacts).zip](https://github.com/phisoft/phisoft-web/files/9771929/Design.6.-.PhiSoft.Contacts.zip)

**Comment by lalgal** [comment]
[Design 7 - PhiSoft (Contacts).zip](https://github.com/phisoft/phisoft-web/files/9772014/Design.7.-.PhiSoft.Contacts.zip)
