### ISSUE TITLE
provide suitable images for phisoft website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#137]
Provide suggestions for website homepage images, ensure that photo is clear and shows more of asians. 

![Image](https://user-images.githubusercontent.com/30463117/203201323-222b36c3-8b37-4abc-b48e-0807899f3787.png)

![Image](https://user-images.githubusercontent.com/30463117/203201341-a68e84d0-652f-4a3f-b727-96494b236dec.png)

![Image](https://user-images.githubusercontent.com/30463117/203201397-6135b4a0-d99b-4734-baee-931bc3640dc3.png)

**Comment by lalgal** [comment]
[IMG.zip](https://github.com/phisoft/phisoft-web/files/10119045/IMG.zip)
