### ISSUE TITLE
plan & design phi software social media content for december 2022

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#139]
- [ ] tech knowledge, tips, etc sharing (provide a few)
- [ ] quotes (provide a few)
- [ ] christmas
- [ ] new year

**Comment by rosclaritha** [comment]
``

**Comment by lalgal** [comment]
[Christmas & New Year's Greeting.zip](https://github.com/phisoft/phisoft-web/files/10273981/Christmas.New.Year.s.Greeting.zip)

**Comment by lalgal** [comment]
[Quotes - Elon Musk.zip](https://github.com/phisoft/phisoft-web/files/10275826/Quotes.-.Elon.Musk.zip)

**Comment by lalgal** [comment]
[Tech Tips - Dec PhiSoft 2022.zip](https://github.com/phisoft/phisoft-web/files/10285104/Tech.Tips.-.Dec.PhiSoft.2022.zip)
