### ISSUE TITLE
create shirt design for phisoft

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#142]
provide a few designs

**Comment by lalgal** [comment]
![T-Shirt Design 1](https://user-images.githubusercontent.com/112998668/215660227-6edc522e-4e9e-4e44-81da-850069d19a4b.jpg)
![T-Shirt Design 2](https://user-images.githubusercontent.com/112998668/215660233-b27fc2a3-c292-4e0f-9bcf-bc4a60f4621a.jpg)
![T-Shirt Design 3](https://user-images.githubusercontent.com/112998668/215660234-35bb4a42-0d9b-4dd9-a0ec-7c627386870d.jpg)

**Comment by lalgal** [comment]
[Shirt Design Vector - Phisoft 2023.zip](https://github.com/phisoft/phisoft-web/files/10542612/Shirt.Design.Vector.-.Phisoft.2023.zip)
