### ISSUE TITLE
Adjust the design

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#18]
Currently look a bit too crowded.
Can split into two rows section, our values followed by our mission. Adding some picture will be nice too.

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/27353/102230493-e6991a80-3f27-11eb-968c-b180e893a3c8.png">

**Comment by izahshahirah** [comment]
done

**Comment by izahshahirah** [comment]
![test](https://user-images.githubusercontent.com/60636305/103738166-7cf3c400-502e-11eb-94a9-fb921d1e397f.jpg)
