### ISSUE TITLE
redesign solution page

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#207]
refer: https://github.com/phisoft/toursbloom-web/issues/86

redesign in figma, share link comment below.
![image](https://github.com/phisoft/phisoft-web/assets/30463117/aec54d85-b619-4898-9af6-14e8e55a903b)

**Comment by sksh70** [comment]
@rosclaritha here's the figma link

1. [Desktop](https://www.figma.com/proto/chvqdlH1kNusatEP3LnqT7/PhiSoft-Solutions-Redesign?page-id=80%3A669&type=design&node-id=80-672&viewport=125%2C826%2C0.49&t=WBLlnf2vk75ASLj6-1&scaling=contain&starting-point-node-id=80%3A672&mode=design)
2. [Mobile](https://www.figma.com/proto/chvqdlH1kNusatEP3LnqT7/PhiSoft-Solutions-Redesign?page-id=99%3A148&type=design&node-id=114-230&viewport=-8008%2C4330%2C1.31&t=vM3Knak9TxSJr0Dh-1&scaling=scale-down&starting-point-node-id=99%3A702&mode=design)

**Comment by rosclaritha** [comment]
give other suggestions @sksh70

**Comment by FaziraFM** [comment]
@paragasu 

Sample Layout 1(original, smaller logo)
![image](https://github.com/phisoft/phisoft-web/assets/147354657/546ff226-2986-41de-87b7-062c22f6742c)

Sample Layout 2
![image](https://github.com/phisoft/phisoft-web/assets/147354657/87fdf10a-6c45-4038-bb46-5bc5d1583dae)
