### ISSUE TITLE
fix link to navigate to services page

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#208]
when click on `Discover Now` button:
![image](https://github.com/phisoft/phisoft-web/assets/30463117/6384908c-c541-497a-982f-0f41818ee680)

Will navigate to correct service page:
![image](https://github.com/phisoft/phisoft-web/assets/30463117/c1268aa6-d64d-4d60-87ef-aae93fdea470)

**Comment by sksh70** [comment]
this one also apply to branch version2? @rosclaritha
