### ISSUE TITLE
Redesign our visions and our values

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#23]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/107747413-5540fb80-6d52-11eb-9171-e06ac1dca652.png">

- [x] Find suitable photo and replace
- [x] Adjust spacing and margins

**Comment by amyleena95** [comment]
![image](https://user-images.githubusercontent.com/43438079/107933964-6a1fc800-6fba-11eb-9961-c436763159f9.png)

or should I customise the pictures?

**Comment by amyleena95** [comment]
second
![image](https://user-images.githubusercontent.com/43438079/107950943-7152d000-6fd2-11eb-95a5-7e74bbe2d587.png)
