### ISSUE TITLE
Replace the text with the following `Join our team for career opportunities and professional growth`

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#230]
<img width="1608" alt="image" src="https://github.com/phisoft/phisoft-web/assets/27353/ce5a9c4d-e428-45ab-8fb7-75c6acba9ab9">

**Comment by AzmirMuda** [comment]
before 
![image](https://github.com/phisoft/phisoft-web/assets/118720025/7c466911-312b-46e1-8817-63add9c61b70)
after
![image](https://github.com/phisoft/phisoft-web/assets/118720025/906b048e-3c97-45b3-a6f1-ace79425dcc3)
