### ISSUE TITLE
Replace footer main category with `Products & Solutions`

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#231]
<img width="687" alt="image" src="https://github.com/phisoft/phisoft-web/assets/27353/bc504275-34fd-4ce8-b9e7-8fc3fb8464cd">

-  [ ] Replace `Currently Hiring` with `Products & Solutions`
-  [ ] List all product and anchor link to solutions section

**Comment by AzmirMuda** [comment]
sir for the solution I need to add the text 'solution' and link it below each product or just create the link for the product?

**Comment by rosclaritha** [comment]
@AzmirMuda  
replace with actual solution, not just change the title. change accordingly. use branch `production`
![image](https://github.com/phisoft/phisoft-web/assets/30463117/b2dbfb6e-f83b-4ec7-953a-400dbb5b0593)
