### ISSUE TITLE
Replace images

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#240]
<img width="1608" alt="image" src="https://github.com/phisoft/feecollec-web/assets/27353/50e7352b-dc81-49ec-8c87-359c3d276e01">

**Comment by FaziraFM** [comment]
IT Outsourcing

- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/820b2f38-f068-495f-8b64-69f6a0604da2)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/fea99c21-a8df-4bc6-ad4c-f6cd40a5292c)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/87d026ea-180b-44db-9816-18301173ff82)

Empowering Business

- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/a1823042-33c3-4d38-b9cc-0ae06c9cd7f5)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/fe1bed38-a864-49da-8bcc-d29c679a581d)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/8bf3213b-7fd6-4b6c-acea-828ca333ec89)

Bleeding Edge Technology
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/d04e4bd6-5c96-43b1-8da8-f2b7006d9378)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/c45d15d6-0f17-4f12-bbcb-f383ed861910)
- [ ]  ![image](https://github.com/phisoft/phisoft-web/assets/147354657/5398637f-877f-4059-8cc7-84528c8ba73f)
