### ISSUE TITLE
Change background picture

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#250]
<img width="1526" alt="image" src="https://github.com/phisoft/phisoft-web/assets/27353/863a857c-9b77-4f99-bb3c-d281011bc419">

**Comment by FaziraFM** [comment]
- Sample 1

![image](https://github.com/phisoft/phisoft-web/assets/147354657/366330a7-3a4f-4e9f-aa86-5acc6768ca4a)
- Sample 2
![image](https://github.com/phisoft/phisoft-web/assets/147354657/ccab089d-790f-48c7-acd8-6f10143d57c4)
- Sample 3
![image](https://github.com/phisoft/phisoft-web/assets/147354657/60204896-b840-44a9-8d8e-a1340e1ca263)
- Sample 4
![image](https://github.com/phisoft/phisoft-web/assets/147354657/5c227a09-73b0-4ac6-828b-ce7f05bd26a4)
![image](https://github.com/phisoft/phisoft-web/assets/147354657/88255aa7-bd01-4c2c-84a2-2d15adb39a2d)
![image](https://github.com/phisoft/phisoft-web/assets/147354657/89ad1e80-dd3c-43f3-bf0e-e850607d7a76)
