### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#39]
[themeforest-cVfsMFJl-strategytech-it-consulting-html5-website-template.zip](https://github.com/phisoft/phisoft-web/files/8021642/themeforest-cVfsMFJl-strategytech-it-consulting-html5-website-template.zip)

**Comment by rosclaritha** [comment]
Added 3 new folders:
(1) documentation
(2) site
(3)sources
<img width="206" alt="image" src="https://user-images.githubusercontent.com/30463117/154230227-d4a42398-fe3f-483b-b48c-e02654b43d87.png">

**Home Page**
![image](https://user-images.githubusercontent.com/30463117/154230423-45222b6b-95db-4299-9722-6eee5089e30e.png)

**About Us Page**
![image](https://user-images.githubusercontent.com/30463117/154230474-5e8e07d0-b5fc-4378-8e9e-299cae57d782.png)

**Single Service Page**
![image](https://user-images.githubusercontent.com/30463117/154230510-a148d994-dfd8-4a51-921d-8a7f8f3849d1.png)

**Contact Us Page**
![image](https://user-images.githubusercontent.com/30463117/154230542-6e7bcebd-99da-4ebf-b900-2e3f497383e0.png)
