### ISSUE TITLE
Remove html tag

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#42]
![IMAGE 2022-02-18 20:19:10](https://user-images.githubusercontent.com/27353/154681760-eb686f4f-5add-488e-8d80-e7818e1219e0.jpg)

**Comment by rosclaritha** [comment]
![image](https://user-images.githubusercontent.com/30463117/154689772-668faa4f-8c9d-44ab-9982-77b956e3ca4a.png)
