### ISSUE TITLE
Add mission & vision

### ISSUE THREAD

**Issue by paragasu** [phisoft/phisoft-web#47]
About Us

What makes Phi Software Sdn. Bhd. different is our persistant toward continously improving our solutions and we are willing to go extra miles to make sure our software solutions exceed our client expected return of investment. We are incorporated with a mission to promote technology adoption, to grow and improve business operations.
As a business entity, we are driven by these missions.
```
    To motivate business growth.
    To motivate business to grow and achieve greater efficiency, profit and values.
```
``` 
  To promote technology adoption.
    To promote software adoption for small company.
```
```
   To encourage innovation.
    To value local creative talents and encourage innovations.
```
```   
To provide Support.
    To provide support small company to grow and compete in global marketplace.
```
 
 
As a team, we hold these values.
```
Respect for people.
We value talents and commited to provide good working environment, proper recognition and credit to our employees.
```  
```
Teamwork and collaboration.
We work as a team to collaborate and share our passion to create great software.
```

```
Practical solution.
Simple software made according to your business needs.
````

```
Result driven.
We make software that deliver real business values.
```

**Comment by rosclaritha** [comment]
![image](https://user-images.githubusercontent.com/30463117/154883122-a9a15982-e1f2-4e15-832d-5248c95e68f9.png)
