### ISSUE TITLE
Design company namecard

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#70]
To design company namecard for the following:
(1) JEFFRY LUNGGOT
Position: Director, CTO
Email: jeffry@phisoft.my
Phone: +60128669695

(2) JEANNY JOHANIS
Position: Business Executive
Email: jeanny@phisoft.my
Phone: +601112658138

(3) LIZA ROSCLARITHA
Position: Business Executive
Email: rosclaritha@phisoft.my
Phone: +60143555463

**Comment by russel0907** [comment]
Design company namecard:
![Artboard 1@4x-100](https://user-images.githubusercontent.com/94702093/160135137-3232f19e-5e08-4c8b-b16b-4c9986b3bc56.jpg)
