### ISSUE TITLE
Add product website link on title & photo

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#76]
![image](https://user-images.githubusercontent.com/30463117/165216849-bbdec359-319b-4942-915c-9ae0d4211bec.png)

**Comment by russel0907** [comment]
## Add product website link on title & photo;

![Our-Solutions-—-Firefox-Developer-Edition-2022-05-25-16-07-34](https://user-images.githubusercontent.com/94702093/170214141-05b5627c-28ef-4520-afaa-6da3d84c4e10.gif)
