### ISSUE TITLE
Optimize SEO for website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#79]
- [x] research keywords
- [x] research methods on how to increase website conversion
- [x] research methods on how to apply SEO

**Comment by russel0907** [comment]
SEO Checker For Phi Software Website;
https://smallseotools.com/website-seo-score-checker/

## Result
![Screenshot 2022-07-04 at 14-36-06 SEO Checker - Check website SEO score SmallSEOTools](https://user-images.githubusercontent.com/94702093/177095760-c411d32c-ff96-4f69-be08-ea7b411490b8.png)

**Comment by russel0907** [comment]
## work
![add meta](https://user-images.githubusercontent.com/94702093/177109783-fa4a585e-0a28-4e2e-ad72-760f93bd5dc6.png)

## Method to Increase Website Conversion
1. Meta Description. Add Keyword phrase in post title, meta description. Google help to detect the frequent words searched.
2. Think of what people are looking for in their problem’s solution. Eg; To use long tail Keywords. The very specific words used to search what people looking for. Not too general, too long and too short keywords.
5. Website’s Optimization. How the website affects user interactivity & experience

## Applying SEO to Website
1. Add Meta Description.    
2. Make the website load faster. Optimize resources; Images
3. Update content. Eg; alternatives text for images
