### ISSUE TITLE
Add Careers section 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#82]
- [x] Add `Careers` page
- [x] Design the section and put the list below vacancies:

1. Senior Python Developer
=======================
Your responsibilities:

- Design & develop geo-distributed provisioning and scale-out services using Python.
- Design and develop REST API and integration points for various platform services.
- Improve existing features to maximize performance, scalability, and reliability.
- Bring in knowledge of industry best practices and evolve our technology footprint.

Our requirements:
8+ years of industry experience in Python building core features for distributed systems in a Linux environment.
Developer level experience with one or more of the following - Kubernetes, AWS or GCP.
Strong computer science fundamentals - Data structures, Algorithms, Graphs and Distributed Systems concepts.
Solid understanding of HTTP / Authentication / Web services / REST API.

2. Senior JS Developer
===================
What You Will Do:

- Design and develop core features of the product.
- Build reusable code and libraries for future use.
- Improve existing features to maximize performance, usability, and reliability.
- Bring in knowledge of industry best practices and evolve our technology footprint.
- Be the voice behind technological direction and decisions about UI strategy.

Who You Are:
- 8+ years experience in building responsive UI for high performance applications.
- Strong understanding of JavaScript/Typescript, its quirks, and workarounds.
- Good knowledge of Node.js and frameworks available for it.
- Experience with Microservices, WebSockets, Caching or Messaging technologies
- Experience with web front-end technologies like HTML5, CSS3, LESS, SCSS, Bootstrap, React.
- Good understanding of browser rendering behavior and performance, cross-browser compatibility issues, and ways to work around.
- Understanding of differences between multiple delivery platforms, such as mobile vs. desktop, and optimizing output to match the specific platform.
- Strong computer science fundamentals - data structures and algorithms.

3. Senior QA Automation Engineer
=============================
What You Will Do:
- Analyze requirements, review technical design, and build and maintain test case plans and automation for UI, API, and Database functionalities.
- Research, identify, and implement newer test automation technologies.
- Participate in design reviews and product improvement activities.
- Build & maintain requirement / test case/ test result traceability matrix.
- Build & automate the test cases for continuous integration.
- Analyze test results along with failure analysis, utilize fact / data driven metrics to continuously improve test efficiency and effectiveness
- Ensure measurable improvement of product quality by identifying, developing and implementing innovative QA capabilities, strategies, approaches and services.
- Escalate issues, concerns and risk proactively.

Who You Are:
- Experienced with test automation on SaaS applications, APIs, and Databases.
- 5+ years experience developing test automation using Python. Java experience preferred.
- Experienced with scale and performance testing of distributed systems/databases.
- Strong computer science fundamentals, including data structures, distributed algorithms, and software design (formal degrees are not necessary)
- Excellent troubleshooting and problem-solving skills.
- Ability to think creatively and innovate.
- A desire to deliver the best software possible that just works!

**Comment by russel0907** [comment]
## Career page
![Screenshot 2022-07-27 at 16-41-00 About us](https://user-images.githubusercontent.com/94702093/181207065-7e308c73-53cf-47d9-a67f-a3db8ad36820.png)
