### ISSUE TITLE
Make footer `Currently Hiring` same with other page

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#84]
Follow `Home` footer content. Check other pages and make it similar to home footer.
![image](https://user-images.githubusercontent.com/30463117/182511080-313311a2-6275-4e6b-a6fa-d03114800401.png)

**Comment by russel0907** [comment]
## Update footer section add more list for the currently hiring column

![footer](https://user-images.githubusercontent.com/94702093/182535116-0a696593-2bbe-438d-b410-0417c680fac9.png)
