### ISSUE TITLE
Suggest new tagline for website header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#92]
List the suggestions on the comment below:
![image](https://user-images.githubusercontent.com/30463117/186800167-7c64f3a2-fcc3-4e72-a6bb-7ede9c1fe556.png)

**Comment by Suzitaothman** [comment]
1. Platform to Solve Your Problem
2. Your Problem, Our Solution
3. A Better Online solution 
4. Digital Problem-Solver
5. We plan and make it real
6. A Step to a Business-changing
7. Trust us to make a difference in your business

**Comment by rosclaritha** [comment]
@Suzitaothman Change this description:
![image](https://user-images.githubusercontent.com/30463117/187333124-4b273c0f-2641-4ab5-959e-f8a324e832fa.png)

**Comment by Suzitaothman** [comment]
1. We are a software development company that takes pride in building custom-made software. Let us help you find the best solution for you
2. We offer custom software development services for any of your projects,
3. we build custom software for clients with our team of expert developers, we solve all types of requirements from clients in the different type of apps.
4. Our company focuses on providing a custom software development service. We have expert experience in building high-quality and well-designed software that meets the requirements of the client
5. We help our clients to create custom software solutions by providing cost-effective, enterprise-class software development services. 
6. We are a software development company that helps build client-specific solutions. Our team brings experience and knowledge to build custom software, providing professional consultation throughout the entire process.

**Comment by paragasu** [comment]
need something related to the tagline `Leading Business Forward`
