### ISSUE TITLE
Suggest design for the header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/phisoft-web#98]
Provide suggestions on the header design. Place the suggestions on the comments below:
![image](https://user-images.githubusercontent.com/30463117/188801359-9574b381-db4c-43f3-bdeb-841c7abd9d04.png)

**Comment by lalgal** [comment]
[Phi Software Website Banner.zip](https://github.com/phisoft/phisoft-web/files/9546186/Phi.Software.Website.Banner.zip)
